### PR TITLE
This change makes color indexes to be determined by hash of the ident…

### PR DESCRIPTION
**Pull request by aboytsov**
…ifier, which is nice as the same identifiers shows up in the same color accross all buffers.

### CODE REVIEW

**Comment by ankurdave** [comment]
I prefer the sequential coloring approach since it does a better job of reducing color collisions within the same buffer, but if others express interest in the hashing approach, we could keep both and add a configuration variable.

**Comment by syl20bnr** [comment]
:+1: 
I use the stable color across buffers to quickly spot typos.

**Comment by dakrone** [comment]
+1 to keeping stable colors, it'd be nice to be able to get used to a certain var being a certain color :)

**Comment by alphapapa** [comment]
I would also like an option for this.  I like the wider variety of colors, and hash-specific colors, of `rainbow-identifiers`, but that package hasn't been updated in a couple of years, and it seems to have some dead code in it (e.g. the `l*a*b*` functions don't seem to be actually used, preventing customization as the options suggest).

So if this were implemented, it might obsolete `rainbow-identifiers`...

**Comment by dakrone** [comment]
Ping @ankurdave any update on this?

**Comment by ankurdave** [comment]
I just added `color-identifiers-coloring-method`, which you can set to `hash` to get this behavior. Feedback is welcome.

**Comment by alphapapa** [comment]
@ankurdave Thanks, this is neat.  I noticed that it doesn't seem possible to get more than 50 unique colors, even when `color-identifiers:num-colors` is set to a higher number.  I set `n` in the regenerate-color function to 16, and that enabled up to 226 unique colors, but it was very slow to run.  

It would be useful to have more than the default of 10 unique colors.  But just setting it to 50 seems to give a lot of colors that are very similar.  I tried shuffling the list of colors to improve the variety, and it seemed to help some, but the colors still seem biased toward particular colors (e.g. there are a lot of pinks).

**Pull request closed without merging**
