### PR TITLE
Enable CI for pull-requests

### PR DESCRIPTION
**Pull request by Hi-Angel**

### CODE REVIEW

**Comment by Hi-Angel** [comment]
@ankurdave to continue [this discussion](https://github.com/ankurdave/color-identifiers-mode/pull/113#issuecomment-1495054407), so, I did some tests on a test repo, and apparently making CI work requires enabling it in project settings. Here's what it looks like for my test project:

image

Can you please take a look at it?

**Comment by ankurdave** [comment]
CI would be great! It seems like the settings already defaulted to "allow", but I clicked Actions Permissions -> Save anyway just in case. Here's what I see:

Screen Shot 2023-04-05 at 9 12 25 AM

**Comment by ankurdave** [comment]
I clicked through the onboarding workflow in the Actions tab, which created a `ci.yml` file that seems to work. (I made some missteps first, sorry for the commit pollution.) I'm not sure why it didn't work in https://github.com/ankurdave/color-identifiers-mode/pull/113, but hopefully it should work now?

**Comment by Hi-Angel** [comment]
Oh, that sounds great, thank you! I'll experiment more with it this evening, thanks again!

**Comment by Hi-Angel** [comment]
Nice, thanks! Now it works, gotta figure out how to get an image with both `ninja` and Emacs — of these 3 the build system for some reason is only present in one image.

**Comment by Hi-Angel** [comment]
Hmm, FTR, apparently tests may fail on older Emacs releases because of [this bug](https://emacs.stackexchange.com/questions/42306/using-equal-including-properties-to-compare-string-and-propertized-string). Gotta think of a workaround or something…

**Comment by Hi-Angel** [comment]
It's interesting that Github has no button like "Merge when CI passed", like in Gitlab.

Anyway, now we have a working CI, yay!

**Pull request merged**
